<<<<<<< HEAD
# Generated by Django 4.2.19 on 2025-02-21 15:01
=======
# Generated by Django 4.2.19 on 2025-02-18 11:03
>>>>>>> 6bfeeeae0cddbbab539bf71c6fdf2fb76bf8b78d

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectionLog",
            fields=[
                ("collection_id", models.AutoField(primary_key=True, serialize=False)),
                ("collected_by_customer", models.CharField(max_length=100)),
                ("time_collected", models.DateTimeField()),
                ("mode_of_collection", models.CharField(max_length=7)),
            ],
            options={
                "db_table": "collection_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LabRequest",
            fields=[
                ("request_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_requested", models.DateField()),
                ("physician", models.CharField(blank=True, max_length=100, null=True)),
                ("mode_of_release", models.CharField(max_length=7)),
                ("overall_status", models.CharField(max_length=11)),
            ],
            options={
                "db_table": "lab_request",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("last_name", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=50)),
                (
                    "middle_initial",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("suffix", models.CharField(blank=True, max_length=5, null=True)),
                ("sex", models.CharField(max_length=6)),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("mobile_num", models.JSONField(blank=True, null=True)),
                ("landline_num", models.JSONField(blank=True, null=True)),
                ("pwd_id_num", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "senior_id_num",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.JSONField(blank=True, null=True)),
                ("house_num", models.CharField(blank=True, max_length=10, null=True)),
                ("street", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "subdivision",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("baranggay", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(max_length=50)),
                ("province", models.CharField(blank=True, max_length=50, null=True)),
                ("zip_code", models.JSONField(blank=True, null=True)),
                ("civil_status", models.CharField(max_length=7)),
                ("date_added", models.DateField()),
            ],
            options={
                "db_table": "patient",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TemplateField",
            fields=[
                ("field_id", models.AutoField(primary_key=True, serialize=False)),
                ("label_name", models.CharField(max_length=255)),
                ("field_type", models.CharField(max_length=6)),
                ("field_fixed_value", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "template_field",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TemplateForm",
            fields=[
                ("template_id", models.AutoField(primary_key=True, serialize=False)),
                ("template_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "template_form",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TemplateSection",
            fields=[
                ("section_id", models.AutoField(primary_key=True, serialize=False)),
                ("section_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "template_section",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TestComponent",
            fields=[
                ("component_id", models.AutoField(primary_key=True, serialize=False)),
                ("test_code", models.CharField(max_length=20)),
                ("test_name", models.CharField(max_length=100)),
                (
                    "component_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("category", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "test_component",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TestPackage",
            fields=[
                ("package_id", models.AutoField(primary_key=True, serialize=False)),
                ("package_name", models.CharField(max_length=100)),
                ("package_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "test_package",
                "managed": False,
=======
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionLog',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('collected_by_customer', models.CharField(max_length=100)),
                ('time_collected', models.DateTimeField()),
                ('mode_of_collection', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'collection_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_requested', models.DateField()),
                ('physician', models.CharField(blank=True, max_length=100, null=True)),
                ('mode_of_release', models.CharField(max_length=7)),
                ('overall_status', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'lab_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('suffix', models.CharField(blank=True, max_length=5, null=True)),
                ('sex', models.CharField(max_length=6)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('mobile_num', models.JSONField(blank=True, null=True)),
                ('landline_num', models.JSONField(blank=True, null=True)),
                ('pwd_id_num', models.CharField(blank=True, max_length=20, null=True)),
                ('senior_id_num', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.JSONField(blank=True, null=True)),
                ('house_num', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('subdivision', models.CharField(blank=True, max_length=100, null=True)),
                ('baranggay', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.JSONField(blank=True, null=True)),
                ('civil_status', models.CharField(max_length=7)),
                ('date_added', models.DateField()),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=6)),
                ('field_fixed_value', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'template_field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateForm',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'template_form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'template_section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestComponent',
            fields=[
                ('component_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_code', models.CharField(max_length=20)),
                ('test_name', models.CharField(max_length=100)),
                ('component_price', models.JSONField()),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'test_component',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestPackage',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=100)),
                ('package_price', models.JSONField()),
            ],
            options={
                'db_table': 'test_package',
                'managed': False,
>>>>>>> 6bfeeeae0cddbbab539bf71c6fdf2fb76bf8b78d
            },
        ),
    ]
