# Generated by Django 4.2.19 on 2025-02-26 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labreqsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestComponent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'request_component',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestLineItem',
            fields=[
                ('line_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'request_line_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestPackage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'request_package',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestPackageComponent',
            fields=[
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='labreqsys.testpackage')),
            ],
            options={
                'db_table': 'test_package_component',
                'managed': False,
            },
        ),
    ]
