# Generated by Django 4.2.19 on 2025-04-15 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labreqsys', '0002_requestcomponent_requestlineitem_requestpackage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTech',
            fields=[
                ('lab_tech_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=30)),
                ('tech_role', models.CharField(max_length=30)),
                ('license_num', models.CharField(max_length=50)),
                ('signature_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lab_tech',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultValue',
            fields=[
                ('result_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'result_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultReview',
            fields=[
                ('lab_tech', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='labreqsys.labtech')),
                ('reviewed_date', models.DateField()),
            ],
            options={
                'db_table': 'result_review',
                'managed': False,
            },
        ),
    ]
