# Generated by Django 4.2.19 on 2025-04-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labreqsys', '0003_labtech_resultvalue_resultreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultreview',
            name='lab_tech',
        ),
        migrations.DeleteModel(
            name='ResultValue',
        ),
        migrations.DeleteModel(
            name='LabTech',
        ),
        migrations.DeleteModel(
            name='ResultReview',
        ),
    ]
