# Generated by Django 5.2 on 2025-05-14 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labreqsys', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditPatientPasscode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='labreqsys.patient')),
            ],
        ),
    ]
